apiVersion: v1
kind: Service
metadata:
  name: opa
  labels:
    app: opa
    role: master
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8181
    targetPort: 8181
  selector:
    app: opa
    role: master
    tier: backend
